apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentinel-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
        context: sentinel
        version: v1
    spec:
      containers:
      -
        name: app
        image: docker.io/hashneo/sentinel-webhook-x86_64:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "5000"
        - name: CONSUL
          value: consul
        - name: NEW_RELIC_NO_CONFIG_FILE
          value: "false"
        ports:
        -
          containerPort: 5000
          protocol: TCP
